import { z } from "zod";
import { HashableJsonValueSchema, Sha256HashSchema } from "./hashable-json.js";
import { DependenciesSchema, ItemTypeSchema, SlugSchema, TitleSchema } from "./meta.js";
import { RelativePathSchema } from "./paths.js";
import { SemverVersionSchema } from "./semver.js";

/** Registry format version. The CLI refuses unknown future major versions. */
export const SCHEMA_VERSION = 1 as const;

/** `files[].variant` default, materialized before hashing (see hash.ts). */
export const DEFAULT_VARIANT = "ts-tw" as const;

/** Tailwind v3 config fragments the CLI merges (keyframes/animation). */
export const TailwindFragmentSchema = z
  .object({
    keyframes: z.record(z.string(), HashableJsonValueSchema).optional(),
    animation: z.record(z.string(), HashableJsonValueSchema).optional(),
  })
  .strict();

export type TailwindFragment = z.infer<typeof TailwindFragmentSchema>;

/** CSS variables for Tailwind v4 `@theme` blocks (light/dark). */
export const CssVarsSchema = z
  .object({
    light: z.record(z.string(), HashableJsonValueSchema).optional(),
    dark: z.record(z.string(), HashableJsonValueSchema).optional(),
  })
  .strict();

export type CssVars = z.infer<typeof CssVarsSchema>;

/**
 * Optional per-component `styles.json` (Task 4a decision D2): `{ tailwind?, cssVars? }`.
 * Reuses the exact sub-schemas of RegistryItemSchema — no duplicated definitions.
 */
export const ComponentStylesSchema = z
  .object({
    tailwind: TailwindFragmentSchema.optional(),
    cssVars: CssVarsSchema.optional(),
  })
  .strict();

export type ComponentStyles = z.infer<typeof ComponentStylesSchema>;

export const RegistryFileSchema = z
  .object({
    path: RelativePathSchema,
    content: z.string().min(1, "file content must not be empty"),
    type: ItemTypeSchema,
    variant: z.string().min(1).max(32).default(DEFAULT_VARIANT),
  })
  .strict();

export type RegistryFile = z.infer<typeof RegistryFileSchema>;

/**
 * Registry item `/r/<slug>.json`, generated by the builder, read by the CLI
 * (MASTER_PROMPT Section 4.2). `.strict()`: unknown keys are rejected.
 */
export const RegistryItemSchema = z
  .object({
    schemaVersion: z.literal(SCHEMA_VERSION),
    slug: SlugSchema,
    type: ItemTypeSchema,
    title: TitleSchema,
    version: SemverVersionSchema,
    hash: Sha256HashSchema,
    dependencies: DependenciesSchema.default({}),
    registryDependencies: z.array(SlugSchema).default([]),
    files: z
      .array(RegistryFileSchema)
      .min(1, "item must contain at least one file")
      .refine(
        (files) => new Set(files.map((file) => file.path)).size === files.length,
        "file paths must be unique within one item",
      )
      .refine(
        (files) =>
          new Set(files.map((file) => file.path.toLowerCase().normalize("NFC"))).size ===
          files.length,
        "file paths must be unique within one item (case-insensitive)",
      ),
    tailwind: TailwindFragmentSchema.optional(),
    cssVars: CssVarsSchema.optional(),
  })
  .strict();

export type RegistryItem = z.infer<typeof RegistryItemSchema>;
